### ISSUE TITLE
Add ability to edit manager field for Chatter Free users

### ISSUE THREAD

**Issue by douglascayers** [DouglasCAyers/sfdc-chatter-org-chart#1]
Salesforce out of the box doesn't let you specify the Manager of a user to reference a Chatter Free user when editing the user's profile in the UI. However, this is not a system limitation as you can assign the manager field via apex or data loader. It would be nice if this org chart page had a way to change the manager of a user regardless the license type (e.g. standard, chatter free, etc).

Idea inspired by @office_gnome
https://twitter.com/DouglasCAyers/status/557778811388166144

**Comment by douglascayers** [comment]
This feature has been delivered with latest commits. Readme has been updated with new screen shots and details.

**Comment by Jermetz** [comment]
@DouglasCAyers This feature has been delivered? where and when do i find it?

**Comment by douglascayers** [comment]
Hi @Jermetz, you can deploy the latest code by clicking the "Deploy to Salesforce" button at the top of the README when at the project main page, https://github.com/DouglasCAyers/sfdc-chatter-org-chart

Once the new code is deployed, system administrators (or users with 'manage user' permission) will see the blue pencil icon in the upper-right of the Org Chart page.
